apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kmac2-7086"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kmac2-7086"
  template:
    metadata:
      labels:
        app: "kmac2-7086"
    spec:
      containers:
        - name: "kmac2-7086"
          image: "kaj21.azurecr.io/kmac2"
          ports:
          - containerPort: 80